name: PnP_iBPDCA
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8.19
  - pytorch==2.2.0
  - torchvision==0.17.0
  - torchaudio==2.2.0
  - torchmetrics==0.5.0
  - pytorch-cuda=11.8
  - pytorch-lightning==1.2.4
  - pip
  - pip:
    - piq
    - opencv-python
    - matplotlib
    - scikit-image
    - scipy

